import { button } from "./Button/button";
import { p } from "./P/p";
import { nav } from "./Nav/nav";
import { span } from "./Span/span";
import { div } from "./Div/div";
import a from "./A/a";
import { form } from "./Form/form";
import { input } from "./Input/input";
import { ul } from "./Ul/ul";
import { li } from "./Li/li";
import { orangeBoard } from "./Div/orangeBoard";
import { TaskList } from "./TaskGroup/TaskList";
import { Header } from "./TaskGroup/Header";
import { Wrapper } from "./TaskGroup/Wrapper";
import { img } from "./Img/img";
import { h1 } from "./H1/h1";
import { h4 } from "./H4/h4";
import { h5 } from "./H5/h5";
import { hr } from "./Hr/hr";
import { small } from './Small/small';
import { footer } from "./Footer/footer";
import { loginWrapper } from "./Div/loginWrapper";
import { label } from "./Label/label";
import { textarea } from "./Textarea/textarea";
import { select, option } from "./Select/select";

export const Button = button;
export const Paragraph = p;
export const Nav = nav;
export const Span = span;
export const Div = div;
export const A = a;
export const Form = form;
export const Input = input;
export const TextArea = textarea;
export const Select = select;
export const Option = option;
export const Ul = ul;
export const Li = li;
export const OrangeBoard = orangeBoard;
export const Img = img;
export const H1 = h1;
export const H4 = h4;
export const H5 = h5;
export const Hr = hr;
export const Small = small;
export const Label = label;
export const Footer = footer;
export const LoginWrapper = loginWrapper;

// Task group
export const TaskGroupWrapper = Wrapper;
export const TaskGroupHeader = Header;
export const TaskGroupList = TaskList;